Page:
  in: query
  name: page
  type: integer
  description: 'Page # in the collection'

ItemsPerPage:
  in: query
  name: per_page
  type: integer
  description: How many documents per page?
    
SearchQuery:
  in: query
  name: q
  type: string 
  description: Search query content

ApiKeyHeader:
  in: header
  name: X-Api-Key
  schema:
    type: string
  required: true
  example: 5c29112cbb65c135bbe51179